ALTER TABLE "Partner" ADD COLUMN "adminOnly" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Brand" ADD COLUMN "adminOnly" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Deal" ADD COLUMN "adminOnly" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Asset" ADD COLUMN "adminOnly" BOOLEAN NOT NULL DEFAULT false;
