"use client";

import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { IntakeLinkDialog } from "@/components/dashboard/IntakeLinkDialog";
import { IntakeConvertDialog } from "@/components/dashboard/IntakeConvertDialog";

interface Submission {
  submissionId: string;
  companyName: string;
  websiteDomain: string | null;
  brandName: string;
  brandDomain: string | null;
  trackingDomain: string | null;
  targetGeos: string[];
  licenseInfo: string | null;
  contactName: string;
  contactEmail: string;
  contactPhone: string | null;
  preferredContact: string | null;
  notes: string | null;
  status: string;
  submittedAt: string;
  intakeLink: {
    createdBy: { name: string };
  };
}

const statusColors: Record<string, string> = {
  Pending: "bg-yellow-100 text-yellow-800",
  Converted: "bg-green-100 text-green-800",
  Rejected: "bg-red-100 text-red-800",
};

export default function IntakePage() {
  const [tab, setTab] = useState("Pending");
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [loading, setLoading] = useState(true);
  const [linkDialogOpen, setLinkDialogOpen] = useState(false);
  const [convertDialogOpen, setConvertDialogOpen] = useState(false);
  const [selectedSubmission, setSelectedSubmission] = useState<Submission | null>(null);

  const fetchSubmissions = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/intake-submissions?status=${tab}`);
      if (res.ok) {
        const data = await res.json();
        setSubmissions(data);
      }
    } catch {
      // silent
    } finally {
      setLoading(false);
    }
  }, [tab]);

  useEffect(() => {
    fetchSubmissions();
  }, [fetchSubmissions]);

  function handleRowClick(submission: Submission) {
    setSelectedSubmission(submission);
    setConvertDialogOpen(true);
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Intake</h1>
        <Button onClick={() => setLinkDialogOpen(true)}>Generate Link</Button>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList>
          <TabsTrigger value="Pending">Pending</TabsTrigger>
          <TabsTrigger value="Converted">Converted</TabsTrigger>
          <TabsTrigger value="Rejected">Rejected</TabsTrigger>
        </TabsList>

        <TabsContent value={tab} className="mt-4">
          {loading ? (
            <p className="py-8 text-center text-muted-foreground">Loading...</p>
          ) : submissions.length === 0 ? (
            <p className="py-8 text-center text-muted-foreground">
              No {tab.toLowerCase()} submissions.
            </p>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Company</TableHead>
                    <TableHead>Brand</TableHead>
                    <TableHead>Contact</TableHead>
                    <TableHead>Submitted</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {submissions.map((sub) => (
                    <TableRow
                      key={sub.submissionId}
                      className="cursor-pointer"
                      onClick={() => handleRowClick(sub)}
                    >
                      <TableCell className="font-medium">
                        {sub.companyName}
                      </TableCell>
                      <TableCell>{sub.brandName}</TableCell>
                      <TableCell>
                        <div>{sub.contactName}</div>
                        <div className="text-xs text-muted-foreground">
                          {sub.contactEmail}
                        </div>
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {new Date(sub.submittedAt).toLocaleDateString()}
                      </TableCell>
                      <TableCell className="text-sm">
                        {sub.intakeLink.createdBy.name}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant="secondary"
                          className={statusColors[sub.status] ?? ""}
                        >
                          {sub.status}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </TabsContent>
      </Tabs>

      <IntakeLinkDialog
        open={linkDialogOpen}
        onOpenChange={setLinkDialogOpen}
        onSuccess={() => {}}
      />

      <IntakeConvertDialog
        open={convertDialogOpen}
        onOpenChange={setConvertDialogOpen}
        submission={selectedSubmission}
        onSuccess={fetchSubmissions}
      />
    </div>
  );
}
